### PR TITLE
fix: throw a Forbidden error if username doesn't match

### PR DESCRIPTION
**Pull request by afmotta**
With the current implementation, in case of a mismatch between the username in the request and the one from the JWT,
the endpoints ignores the username in the request and just returns data for the authenticated user.

A more robust and correct behaviour would be to return a 403 Forbidden error.

Partially addresses #50

### CODE REVIEW

**Comment by groozin** [comment]
Super cool. First of all - please look here: https://github.com/nearform/owasp-top-ten-workshop/issues/50
This is our list of problems and suggestions after the initial walkthrough. The problem you are fixing is on that list ❤️. Please do the following:
 - the issue you basically addressed is in the `Suggestions` section under: `step1test`: that sounds more like `/me` endpoint and maybe a little too contrived example - but definitely explains the vulnerability. If possible please edit that issue and put your login next to that sentence.
 - link issue #50 with your PR

**Comment by groozin** [comment]
The code looks good. If we want to merge this PR though we need to change the content on the `slides.md` as well. Please change to contents of slides 14 and 15 to incorporate the `403` response instead of returning the logged-in user's profile.

**Review by groozin — CHANGES_REQUESTED** [review]
The code looks good. If we want to merge this PR though we need to change the content on the slides.md as well. Please change to contents of slides 14 and 15 to incorporate the 403 response instead of returning the logged-in user's profile.

**Review by washingtonsoares — APPROVED** [review]

**Comment by afmotta** [comment]
Hey @groozin thanks for your comment.
I've already updated all the slides touched by the PR.

I don't seem to have the permissions to update #50

**Comment by groozin** [comment]
About slides - I meant something along the lines of (slide 15) 
> - The server should instead fetch the logged-in user's info
And maybe changing it to explicitly mention `403` error. 

That being said. I can take it from here. Will change the wording on the slides.

**Review by groozin — APPROVED** [review]

**Pull request merged**
